FROM dockerfile_deb_vi

# COPY jdk-21_linux-x64_bin.tar.gz /tmp/
# RUN tar -xzvf /tmp/jdk-21_linux-x64_bin.tar.gz -C /opt/
# ENV PATH=$PATH:/opt/jdk-21.0.1/bin

ADD ./jdk-21_linux-x64_bin.tar.gz /usr

ENV PATH=$PATH:/usr/jdk-21.0.1/bin