version: '3'

services:
  apache:
    image: docker_deb_php
    ports:
      - "80:80"

      #construire l'image à partir du dockerfile
    build: ../debian_php
    volumes:
      - ./www:/var/www/html #sauvegarde des modif en local
    restart: always
    container_name: website

  mysql:
    image : mysql
    # restart : always
    environment :
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:bdd
      - MYSQL_USER:toto
      - MYSQL_PASSWORD:toto
    ports : 
      - 3306:3306
    container_name : bdd
    volumes :
      - ./data:/var/lib/mysql


  # Configuration de l'image phpmyadmin

  phpmyadmin :
    image: phpmyadmin
    restart: always
    ports: 
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
      - PMA_HOST=bdd
      - PMA_PORT=3306
    container_name : php


networks:
  - rezo